import {
  ALL_APPLICATIONS,
  route,
  type GatewayRoutePolicy,
} from "./route-policy.core";

export const AUTH_ROUTES: readonly GatewayRoutePolicy[] = Object.freeze([
  route({
    id: "auth.register",
    method: "POST",
    path: "/api/v1/auth/register",
    applications: ALL_APPLICATIONS,
    actor: "anonymous",
    downstreamTarget: "auth-service",
    downstreamRpc: "AuthService.Register",
    input: "auth-register",
    successStatus: 201,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  route({
    id: "auth.login",
    method: "POST",
    path: "/api/v1/auth/login",
    applications: ALL_APPLICATIONS,
    actor: "anonymous",
    downstreamTarget: "auth-service",
    downstreamRpc: "AuthService.ValidateUser+GetTokens",
    input: "auth-login",
    successStatus: 200,
    response: "action",
    pagination: "none",
    retry: "session",
  }),
  route({
    id: "auth.refresh",
    method: "POST",
    path: "/api/v1/auth/refresh",
    applications: ALL_APPLICATIONS,
    actor: "session",
    downstreamTarget: "auth-service",
    downstreamRpc: "AuthService.RefreshTokens",
    input: "auth-refresh",
    successStatus: 200,
    response: "action",
    pagination: "none",
    retry: "session",
  }),
  route({
    id: "auth.logout",
    method: "POST",
    path: "/api/v1/auth/logout",
    applications: ALL_APPLICATIONS,
    actor: "authenticated",
    downstreamTarget: "auth-service",
    downstreamRpc: "AuthService.Logout",
    input: "auth-logout",
    successStatus: 200,
    response: "action",
    pagination: "none",
    retry: "key",
  }),
  route({
    id: "auth.me",
    method: "GET",
    path: "/api/v1/auth/me",
    applications: ALL_APPLICATIONS,
    actor: "authenticated",
    downstreamTarget: "auth-service",
    downstreamRpc: "AuthService.GetProfile",
    input: "none",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "safe",
  }),
]);
