import {
  adminRoute,
  publicRoute,
  type GatewayRoutePolicy,
} from "./route-policy.core";

export const BLOG_ROUTES: readonly GatewayRoutePolicy[] = Object.freeze([
  publicRoute({
    id: "blog.posts.list",
    method: "GET",
    path: "/api/v1/blog/posts",
    downstreamTarget: "blog-service",
    downstreamRpc: "BlogService.ListPosts",
    input: "blog-list",
    successStatus: 200,
    response: "collection",
    pagination: "page-limit-total",
    retry: "safe",
  }),
  publicRoute({
    id: "blog.posts.get",
    method: "GET",
    path: "/api/v1/blog/posts/:slug",
    downstreamTarget: "blog-service",
    downstreamRpc: "BlogService.GetPost",
    input: "slug",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "safe",
  }),
  adminRoute({
    id: "admin.blog.posts.create",
    method: "POST",
    path: "/api/v1/admin/blog/posts",
    downstreamTarget: "blog-service",
    downstreamRpc: "BlogService.CreatePost",
    input: "blog-write",
    successStatus: 201,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.blog.posts.update",
    method: "PATCH",
    path: "/api/v1/admin/blog/posts/:id",
    downstreamTarget: "blog-service",
    downstreamRpc: "BlogService.UpdatePost",
    input: "blog-patch",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.blog.posts.delete",
    method: "DELETE",
    path: "/api/v1/admin/blog/posts/:id",
    downstreamTarget: "blog-service",
    downstreamRpc: "BlogService.DeletePost",
    input: "uuid-id",
    successStatus: 200,
    response: "action",
    pagination: "none",
    retry: "key",
  }),
]);
