import {
  ALL_APPLICATIONS,
  adminRoute,
  consumerRoute,
  route,
  type GatewayRoutePolicy,
} from "./route-policy.core";

function mediaLaneRoutes(
  lane: "public" | "protected" | "strict",
): readonly GatewayRoutePolicy[] {
  const serviceLane = `${lane[0].toUpperCase()}${lane.slice(1)}Library`;
  const base = `/api/v1/admin/media/${lane}-library`;
  const routes: GatewayRoutePolicy[] = [
    adminRoute({
      id: `admin.media.${lane}.list`,
      method: "GET",
      path: base,
      downstreamTarget: "media-service",
      downstreamRpc: `MediaService.List${serviceLane}`,
      input: lane === "public" ? "media-public-list" : "media-admin-list",
      successStatus: 200,
      response: "collection",
      pagination: "offset-take",
      retry: "safe",
    }),
    adminRoute({
      id: `admin.media.${lane}.presign`,
      method: "POST",
      path: `${base}/presign`,
      downstreamTarget: "media-service",
      downstreamRpc: `MediaService.Presign${serviceLane}Upload`,
      input: "media-presign",
      successStatus: 200,
      response: "action",
      pagination: "none",
      retry: "key",
    }),
    adminRoute({
      id: `admin.media.${lane}.finalize`,
      method: "POST",
      path: `${base}/finalize`,
      downstreamTarget: "media-service",
      downstreamRpc: `MediaService.Finalize${serviceLane}Upload`,
      input: "media-finalize",
      successStatus: 201,
      response: "item",
      pagination: "none",
      retry: "key",
    }),
    adminRoute({
      id: `admin.media.${lane}.read-url`,
      method: "POST",
      path: `${base}/:id/read-url`,
      downstreamTarget: "media-service",
      downstreamRpc: `MediaService.Create${serviceLane}ReadUrl`,
      input: "media-read-url",
      successStatus: 200,
      response: "action",
      pagination: "none",
      retry: "key",
    }),
  ];
  if (lane !== "public") {
    routes.push(
      adminRoute({
        id: `admin.media.${lane}.delete`,
        method: "DELETE",
        path: `${base}/:id`,
        downstreamTarget: "media-service",
        downstreamRpc: `MediaService.Delete${serviceLane}ById`,
        input: "uuid-id",
        successStatus: 200,
        response: "action",
        pagination: "none",
        retry: "key",
      }),
    );
  }
  return Object.freeze(routes);
}

export const MEDIA_ROUTES: readonly GatewayRoutePolicy[] = Object.freeze([
  adminRoute({
    id: "admin.media.get",
    method: "GET",
    path: "/api/v1/admin/media/:id",
    downstreamTarget: "media-service",
    downstreamRpc: "MediaService.GetById",
    input: "uuid-id",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "safe",
  }),
  ...mediaLaneRoutes("public"),
  ...mediaLaneRoutes("protected"),
  ...mediaLaneRoutes("strict"),
  consumerRoute({
    id: "media.owned.list",
    method: "GET",
    path: "/api/v1/media/my/protected-library",
    actor: "user",
    downstreamTarget: "media-service",
    downstreamRpc: "MediaService.ListMyProtectedLibrary",
    input: "media-owned-list",
    successStatus: 200,
    response: "collection",
    pagination: "offset-take",
    retry: "safe",
  }),
  consumerRoute({
    id: "media.owned.read-url",
    method: "POST",
    path: "/api/v1/media/my/protected-library/:id/read-url",
    actor: "user",
    downstreamTarget: "media-service",
    downstreamRpc: "MediaService.CreateMyProtectedReadUrl",
    input: "media-owned-read-url",
    successStatus: 200,
    response: "action",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.media.public.delete-preview",
    method: "POST",
    path: "/api/v1/admin/media/public-library/delete-preview",
    downstreamTarget: "media-service",
    downstreamRpc: "MediaService.PreviewPublicLibraryDelete",
    input: "media-delete-preview",
    successStatus: 200,
    response: "action",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.media.public.delete-confirm",
    method: "POST",
    path: "/api/v1/admin/media/public-library/delete-confirm",
    downstreamTarget: "media-service",
    downstreamRpc: "MediaService.ConfirmPublicLibraryDelete",
    input: "media-delete-confirm",
    successStatus: 200,
    response: "action",
    pagination: "none",
    retry: "key",
  }),
  route({
    id: "media.render",
    method: "GET",
    path: "/api/v1/media/render/:id",
    applications: ALL_APPLICATIONS,
    actor: "anonymous",
    downstreamTarget: "media-render-http",
    downstreamRpc: "GET /media/render/:id",
    input: "media-render",
    successStatus: 200,
    response: "stream",
    pagination: "none",
    retry: "stream",
  }),
]);
