import {
  adminRoute,
  consumerRoute,
  type GatewayRoutePolicy,
} from "./route-policy.core";

export const ORDER_ROUTES: readonly GatewayRoutePolicy[] = Object.freeze([
  consumerRoute({
    id: "orders.cart.get",
    method: "GET",
    path: "/api/v1/orders/cart",
    actor: "authenticated",
    downstreamTarget: "order-service",
    downstreamRpc: "OrderService.GetCart",
    input: "none",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "safe",
  }),
  consumerRoute({
    id: "orders.cart.add",
    method: "POST",
    path: "/api/v1/orders/cart/items",
    actor: "authenticated",
    downstreamTarget: "order-service",
    downstreamRpc: "OrderService.AddToCart",
    input: "cart-add",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  consumerRoute({
    id: "orders.cart.update",
    method: "PATCH",
    path: "/api/v1/orders/cart/items/:id",
    actor: "authenticated",
    downstreamTarget: "order-service",
    downstreamRpc: "OrderService.UpdateCartItem",
    input: "cart-update",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  consumerRoute({
    id: "orders.cart.remove",
    method: "DELETE",
    path: "/api/v1/orders/cart/items/:id",
    actor: "authenticated",
    downstreamTarget: "order-service",
    downstreamRpc: "OrderService.RemoveCartItem",
    input: "uuid-id",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  consumerRoute({
    id: "orders.checkout",
    method: "POST",
    path: "/api/v1/orders/checkout",
    actor: "authenticated",
    downstreamTarget: "order-service",
    downstreamRpc: "OrderService.Checkout",
    input: "checkout",
    successStatus: 201,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  consumerRoute({
    id: "orders.list",
    method: "GET",
    path: "/api/v1/orders",
    actor: "authenticated",
    downstreamTarget: "order-service",
    downstreamRpc: "OrderService.ListOrders",
    input: "order-list",
    successStatus: 200,
    response: "collection",
    pagination: "unpaginated",
    retry: "safe",
  }),
  consumerRoute({
    id: "orders.get",
    method: "GET",
    path: "/api/v1/orders/:id",
    actor: "authenticated",
    downstreamTarget: "order-service",
    downstreamRpc: "OrderService.GetOrder",
    input: "uuid-id",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "safe",
  }),
  adminRoute({
    id: "admin.orders.status",
    method: "PATCH",
    path: "/api/v1/admin/orders/:id/status",
    downstreamTarget: "order-service",
    downstreamRpc: "OrderService.UpdateOrderStatus",
    input: "order-status",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
]);
