import {
  adminRoute,
  publicRoute,
  type GatewayRoutePolicy,
} from "./route-policy.core";

export const PRODUCT_ROUTES: readonly GatewayRoutePolicy[] = Object.freeze([
  publicRoute({
    id: "products.list",
    method: "GET",
    path: "/api/v1/products",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.ListProducts",
    input: "product-public-list",
    successStatus: 200,
    response: "collection",
    pagination: "total-only",
    retry: "safe",
  }),
  publicRoute({
    id: "products.get",
    method: "GET",
    path: "/api/v1/products/:id",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.GetProduct",
    input: "uuid-id",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "safe",
  }),
  publicRoute({
    id: "products.gallery.list",
    method: "GET",
    path: "/api/v1/products/:id/gallery",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.ListGallery",
    input: "uuid-id",
    successStatus: 200,
    response: "collection",
    pagination: "unpaginated",
    retry: "safe",
  }),
  adminRoute({
    id: "admin.products.list",
    method: "GET",
    path: "/api/v1/admin/products",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.AdminListProducts",
    input: "product-admin-list",
    successStatus: 200,
    response: "collection",
    pagination: "total-only",
    retry: "safe",
  }),
  adminRoute({
    id: "admin.products.get",
    method: "GET",
    path: "/api/v1/admin/products/:id",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.AdminGetProduct",
    input: "uuid-id",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "safe",
  }),
  adminRoute({
    id: "admin.products.create",
    method: "POST",
    path: "/api/v1/admin/products",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.CreateProduct",
    input: "product-write",
    successStatus: 201,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.products.update",
    method: "PATCH",
    path: "/api/v1/admin/products/:id",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.UpdateProduct",
    input: "product-patch",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.products.delete",
    method: "DELETE",
    path: "/api/v1/admin/products/:id",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.DeleteProduct",
    input: "uuid-id",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.products.restore",
    method: "POST",
    path: "/api/v1/admin/products/:id/restore",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.RestoreProduct",
    input: "uuid-id",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.products.hard-delete",
    method: "DELETE",
    path: "/api/v1/admin/products/:id/hard",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.HardDeleteProduct",
    input: "uuid-id",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.products.bulk-discount",
    method: "POST",
    path: "/api/v1/admin/products/discounts/bulk",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.ApplyDiscountBulk",
    input: "product-bulk-discount",
    successStatus: 200,
    response: "action",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.products.gallery.list",
    method: "GET",
    path: "/api/v1/admin/products/:id/gallery",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.AdminListGallery",
    input: "gallery-admin-list",
    successStatus: 200,
    response: "collection",
    pagination: "unpaginated",
    retry: "safe",
  }),
  adminRoute({
    id: "admin.products.gallery.add",
    method: "POST",
    path: "/api/v1/admin/products/:id/gallery",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.AddImages",
    input: "gallery-add",
    successStatus: 201,
    response: "collection",
    pagination: "unpaginated",
    retry: "key",
  }),
  adminRoute({
    id: "admin.products.gallery.order",
    method: "PUT",
    path: "/api/v1/admin/products/:id/gallery/order",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.ReorderImages",
    input: "gallery-order",
    successStatus: 200,
    response: "collection",
    pagination: "unpaginated",
    retry: "key",
  }),
  adminRoute({
    id: "admin.products.gallery.remove",
    method: "DELETE",
    path: "/api/v1/admin/products/:id/gallery/:imageId",
    downstreamTarget: "product-service",
    downstreamRpc: "ProductService.RemoveImage",
    input: "gallery-remove",
    successStatus: 200,
    response: "collection",
    pagination: "unpaginated",
    retry: "key",
  }),
]);
