import {
  ALL_APPLICATIONS,
  adminRoute,
  route,
  type GatewayRoutePolicy,
} from "./route-policy.core";

export const USER_ROUTES: readonly GatewayRoutePolicy[] = Object.freeze([
  route({
    id: "users.me.get",
    method: "GET",
    path: "/api/v1/users/me",
    applications: ALL_APPLICATIONS,
    actor: "authenticated",
    downstreamTarget: "user-service",
    downstreamRpc: "UserService.GetUser",
    input: "none",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "safe",
  }),
  route({
    id: "users.me.update",
    method: "PUT",
    path: "/api/v1/users/me",
    applications: ALL_APPLICATIONS,
    actor: "authenticated",
    downstreamTarget: "user-service",
    downstreamRpc: "UserService.UpdateProfile",
    input: "profile-update",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "key",
  }),
  adminRoute({
    id: "admin.users.list",
    method: "GET",
    path: "/api/v1/admin/users",
    downstreamTarget: "user-service",
    downstreamRpc: "UserService.ListUsers",
    input: "none",
    successStatus: 200,
    response: "collection",
    pagination: "unpaginated",
    retry: "safe",
  }),
  adminRoute({
    id: "admin.users.get",
    method: "GET",
    path: "/api/v1/admin/users/:id",
    downstreamTarget: "user-service",
    downstreamRpc: "UserService.GetUser",
    input: "uuid-id",
    successStatus: 200,
    response: "item",
    pagination: "none",
    retry: "safe",
  }),
]);
