services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nebula
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    container_name: user-service
    depends_on:
      - postgres
    env_file:
      - apps/user-service/.env
    environment:
      PORT: "3100"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/nebula"
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "3100:3100"

volumes:
  pgdata:
