name: proto-generation-check
on:
  pull_request:
    paths:
      - "packages/protos/**"
      - ".github/workflows/proto-gen.yml"
  push:
    paths:
      - "packages/protos/**"
      - ".github/workflows/proto-gen.yml"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install protoc
        uses: arduino/setup-protoc@v3
      - run: pnpm install --frozen-lockfile
      - run: pnpm proto:gen
      - name: Fail if uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Generated files changed. Run pnpm proto:gen locally and commit."
            git status --porcelain
            exit 1
          fi
